### ISSUE TITLE
you may need this

### ISSUE THREAD

**Issue by gzxultra** [linfeng371/AutoLoginBJUT#1]
I think these might help.

- [README.md template](https://gist.github.com/jxson/1784669)

- [Markdown syntax guide](https://daringfireball.net/projects/markdown/syntax)

- [open-source-licensing](open-source-licensing)

Also, you might need provide automatical method to deloy your script.

**Comment by linfeng371** [comment]
Useful suggestions！Thanks！

**Comment by linfeng371** [comment]
Useful suggestions！Thanks！
